name: CI/CD Diamond Model Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx

    - name: Run data processing
      run: python scripts/data_processing.py

    - name: Train model
      run: python scripts/model_training.py

    - name: Evaluate model
      run: python scripts/model_evaluation.py
